name: Latest posts workflow

on:
  schedule: # Run workflow automatically
    - cron: '0 8 * * *' # Runs every day at 8am
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-dev:
    name: Update README with latest DEV posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.2.5
        with:
          comment_tag_name: "DEV"
          commit_message: "Updated readme with the latest DEV posts"
          feed_list: "https://dev.to/feed/bogdaaamn"
